name: Run tests
on:
  - pull_request
  - push

jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        tox-version: [ 'WTForms2' ]
        include:
          - python-version: 3.6
            tox-version: flake8
          - python-version: 3.6
            tox-version: docs-html
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgis/postgis:12-master # postgres with postgis installed
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: flask_admin_test
        ports:
          - 5432:5432
          # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mongo:
        image: mongo:5.0.4-focal
        ports:
          - 27017:27017
      azurite:
        image: arafato/azurite:2.6.5
        env:
          executable: blob
        ports:
          - 10000:10000
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install postgis
        run: sudo apt-get install -y postgis postgresql-12-postgis-3 postgresql-12-postgis-3-scripts
      - name: Setup postgis
        env:
          PGPASSWORD: postgres
        run: psql -U postgres -h localhost -c 'CREATE EXTENSION hstore;' flask_admin_test
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Run tests
        run: tox -e ${{ matrix.tox-version }}
